name: CI

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  contracts:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    # Start era test node
    - name: Pre-Anvil ZKsync Action
      uses: dutterbutter/era-test-node-action@66121581304ee2d4f0c1c2de46a3d08f1c2f5264

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.11.0

    - name: Use Node.js
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
      with:
        node-version: lts/Iron
        cache: 'pnpm'

    # Install dependencies for repo
    - name: Install dependencies
      run: pnpm install -r --frozen-lockfile

    # Build contracts and generate types
    - name: Build contracts
      run: pnpm build

    # Run contract tests
    - name: Run contract test
      run: pnpm test

