name: "Deploy NFT Quest Testnet"
on:
  push:
    branches: [ "main" ]
    paths:
      - "examples/nft-quest/**"
      - "packages/sdk/**"
  workflow_dispatch:

env:
  HUSKY: 0
  CI: true

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.11.0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/Iron
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install -r --frozen-lockfile

      - name: Build apps
        run: pnpm nx build nft-quest

      - name: Deploy firebase hosting
        uses: matter-labs/action-hosting-deploy@main
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: "${{ secrets.FIREBASE_NFT_QUEST_TESTNET }}"
          projectId: nft-quest-testnet
          target: nft-quest-testnet
          channelId: live
