name: Openchain

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9.11.0

    - name: Use Node.js
      uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
      with:
        node-version: lts/Iron
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install -r --frozen-lockfile

    - name: Run the publishing script
      run: pnpm run openchain

