name: Slither scanner

on: pull_request

jobs:
  slither:
    name: Slither check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.18.0
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: Install foundry-zksync
        run: |
          mkdir ./foundry-zksync
          curl -LO https://github.com/matter-labs/foundry-zksync/releases/download/nightly/foundry_nightly_linux_amd64.tar.gz
          tar zxf foundry_nightly_linux_amd64.tar.gz -C ./foundry-zksync
          chmod +x ./foundry-zksync/forge ./foundry-zksync/cast
          echo "$PWD/foundry-zksync" >> $GITHUB_PATH

      - name: Install Slither
        run: |
          pip install slither-analyzer

      - name: Run Slither
        working-directory: ./
        run: |
          slither --config ./slither.config.json .